minplayers: 4
map: "map1"
spawnworld: "spawn"

teams:
- "red"
- "blue"
- "green"
- "yellow"
- "pink"
- "gray"
- "cyan"
- "orange"

spawn:

boundingbox:
  
beacons:
  
bases:
  
debugmode: true
  
gens:

gentime:
  iron: 10
  gold: 20
  diamond: 30
  emerald: 45
  star: 60
  
respawntime: 5