name: CyberhubBeaconwars
version: 1.17.0
main: net.Cyberhub.tkdkid1000.CyberhubBeaconwars
depend: [WorldEdit, Essentials, helper]
commands:
  debug:
    usage: /debug
    permission: cyberhubbeaconwars.debug
    description: Shows you debug stats for nerds :D
  beacon:
    usage: /beacon <cmd> <args>
    permission: cyberhubbeaconwars.beacon
    description: The main (and only) beaconwars command. To be used by admins only.
  shopgui:
    usage: /shopgui
    permission: cyberhubbeaconwars.shopgui
    description: Opens the beaconwars shop gui.
  enchgui:
    usage: /enchgui
    permission: cyberhubbeaconwars.enchgui
    description: Opens the beaconwars enchantment gui.
  stat:
    usage: /stat
    description: Shows your stats
    aliases: [stats, statistic, statistics]